# Generated by Django 5.1.5 on 2025-02-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=6)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
