# Generated by Django 5.1.5 on 2025-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register_model',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
