# Generated by Django 5.1.5 on 2025-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0002_register_model_address_register_model_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='picture',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
