# Generated by Django 5.1.5 on 2025-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0003_alter_register_model_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_model',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
