# Generated by Django 5.1.5 on 2025-02-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0004_alter_register_model_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='pg_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
