# Generated by Django 5.1.5 on 2025-02-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0005_pg_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sharing', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('landmark', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('rooms', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('Bathroom', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('img1', models.ImageField(upload_to='photos')),
                ('img2', models.ImageField(upload_to='photos')),
                ('img3', models.ImageField(upload_to='photos')),
                ('img4', models.ImageField(upload_to='photos')),
                ('video', models.FileField(upload_to='videos')),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PgConnect_App.pg_type')),
            ],
        ),
    ]
