# Generated by Django 5.1.5 on 2025-02-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0006_add_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg',
            name='Pg_ownerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PgConnect_App.register_model'),
        ),
    ]
