# Generated by Django 5.1.5 on 2025-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0007_add_pg_pg_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
