# Generated by Django 5.1.5 on 2025-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0008_add_pg_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_pg',
            name='sharing',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='add_pg',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
