# Generated by Django 5.1.5 on 2025-02-17 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0009_alter_add_pg_sharing_alter_add_pg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg',
            name='upload_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
