# Generated by Django 5.1.5 on 2025-03-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0011_alter_add_pg_upload_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('property_count', models.IntegerField()),
                ('image', models.ImageField(upload_to='properties/')),
            ],
        ),
    ]
