# Generated by Django 5.1.6 on 2025-04-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PgConnect_App', '0014_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('pg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PgConnect_App.add_pg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PgConnect_App.register_model')),
            ],
        ),
    ]
